import enum

class RoleEnum(str, enum.Enum):
    CITIZEN = "CITIZEN"
    ACADEMIC_VERIFIER = "ACADEMIC_VERIFIER"
    BANK_KYC_OFFICER = "BANK_KYC_OFFICER"
    HOSPITAL_VERIFIER = "HOSPITAL_VERIFIER"
    GOVERNMENT_OFFICER = "GOVERNMENT_OFFICER"
    ADMIN = "ADMIN"
