export const ROUTES = {
  ROOT: '/',
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    VERIFY_OTP: '/verify-otp',
    RESET_PASSWORD: '/reset-password',
  },
  APP: {
    ROOT: '/app',
    DASHBOARD: '/app/dashboard',
    ACTIONS: '/app/actions',
    IDENTITY: '/app/identity',
    DOCUMENTS: '/app/documents',
    DOCUMENT_DETAIL: (id: string) => `/app/documents/${id}`,
    DOCUMENTS_EXPIRING: '/app/documents/expiring',
    FAMILY: '/app/family',
    FAMILY_MEMBER: (id: string) => `/app/family/${id}`,
    FAMILY_DELEGATION: '/app/family/delegation',
    SERVICES: '/app/services',
    SERVICES_GOV: '/app/services/government',
    SERVICES_ORG: '/app/services/organizations',
    SERVICE_DETAIL: (id: string) => `/app/services/${id}`,
    APPLICATIONS: '/app/applications',
    APPLICATION_DETAIL: (id: string) => `/app/applications/${id}`,
    PRIVACY: '/app/privacy',
    SECURITY: '/app/security',
    PAYMENTS: '/app/payments',
    NOTIFICATIONS: '/app/notifications',
    BENEFITS: '/app/benefits',
    DATA_DASHBOARD: '/app/data',
    JOURNEY: '/app/journey',
    ASSISTANT: '/app/assistant',
    PROFILE: '/app/profile',
    SETTINGS: '/app/settings',
  },
  ORGANIZATION: {
    ROOT: '/organization',
    LOGIN: '/organization/login',
    DASHBOARD: '/organization/dashboard',
    PROFILE: '/organization/profile',
    SERVICES: '/organization/services',
    SERVICE_DETAIL: (id: string) => `/organization/services/${id}`,
    APPLICATIONS: '/organization/applications',
    APPLICATION_DETAIL: (id: string) => `/organization/applications/${id}`,
    CITIZENS: '/organization/citizens',
    CITIZEN_DETAIL: (id: string) => `/organization/citizens/${id}`,
    ACCESS_REQUESTS: '/organization/access-requests',
    DOCUMENTS: '/organization/documents',
    MEMBERS: '/organization/members',
    ROLES: '/organization/roles',
    ANALYTICS: '/organization/analytics',
    AUDIT_LOG: '/organization/audit-log',
    SETTINGS: '/organization/settings',
    // ── Advanced Intelligence & Governance Modules ──
    TRUST: '/organization/trust',
    POLICIES: '/organization/policies',
    RECEIPTS: '/organization/receipts',
    INTELLIGENCE: '/organization/intelligence',
    SECURITY_EVENTS: '/organization/security-events',
    ZKP_STUDIO: '/organization/zkp',
    DEVELOPERS: '/organization/developers',
    COMPLIANCE: '/organization/compliance',
  },
  GOVERNMENT: {
    ROOT: '/government',
    LOGIN: '/government/login',
    DASHBOARD: '/government/dashboard',
    SERVICES: '/government/services',
    SERVICE_DETAIL: (id: string) => `/government/services/${id}`,
    APPLICATIONS: '/government/applications',
    APPLICATION_DETAIL: (id: string) => `/government/applications/${id}`,
    CITIZENS: '/government/citizens',
    VERIFICATION: '/government/verification',
    DOCUMENTS: '/government/documents',
    NOTIFICATIONS: '/government/notifications',
    REPORTS: '/government/reports',
    AUDIT_LOG: '/government/audit-log',
    SETTINGS: '/government/settings',
  },
  ADMIN: {
    ROOT: '/admin',
    LOGIN: '/admin/login',
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    ORGANIZATIONS: '/admin/organizations',
    GOVERNMENT: '/admin/government',
    SERVICES: '/admin/services',
    AUDIT: '/admin/audit',
    SETTINGS: '/admin/settings',
  },
  SYSTEM: {
    UNAUTHORIZED: '/unauthorized',
    NOT_FOUND: '/404',
  },
} as const
